sudo: required

services:
  - docker

matrix:
  include:
    - # develop builds and deploys edge
      if: branch = develop
      env:
        global:
          - TRAVIS_GLOBAL=edge
        matrix:
          - CHANNEL=edge LANGUAGE=python2 BASE=ubuntu16
          - CHANNEL=edge LANGUAGE=python3 BASE=ubuntu16
          - CHANNEL=edge LANGUAGE=python2 BASE=ubuntu17
          - CHANNEL=edge LANGUAGE=python3 BASE=ubuntu17
    - # master builds and deploys stable
      if: branch = master
      env:
        global:
          - TRAVIS_GLOBAL=stable
        matrix:
          - CHANNEL=stable LANGUAGE=python2 BASE=ubuntu16
          - CHANNEL=stable LANGUAGE=python3 BASE=ubuntu16
          - CHANNEL=stable LANGUAGE=python2 BASE=ubuntu17
          - CHANNEL=stable LANGUAGE=python3 BASE=ubuntu17

env:
  global:
    - REGISTRY_ORG=sd2e
    - REGISTRY_USER=sd2etest
    - NO_CACHE=1
    # REGISTRY_PASS=...

script:
  - make base-build CHANNEL=$CHANNEL BASE=$BASE NO_CACHE=$NO_CACHE
  - make languages-build CHANNEL=$CHANNEL LANGUAGE=$LANGUAGE BASE=$BASE NO_CACHE=$NO_CACHE
  - make reactors-build CHANNEL=$CHANNEL LANGUAGE=$LANGUAGE NO_CACHE=$NO_CACHE
  - make apps-build CHANNEL=$CHANNEL BASE=$BASE LANGUAGE=$LANGUAGE NO_CACHE=$NO_CACHE

after_script:
  - docker images ${REGISTRY_ORG}/*

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: bash scripts/push_containers_from_ci.sh ${REGISTRY_ORG}
  on:
    branch: master
