sudo: required
services:
  - docker
env:
  - CHANNEL=edge
  - CHANNEL=stable
  global:
    - REGISTRY_ORG=sd2e
    - REGISTRY_USER=sd2etest
    # REGISTRY_PASS=...

script:
  - make base-build
  - make lang-build
  - make apps-build
  - make jupyter-build
  - make reactors-build

after_script:
  - docker images REGISTRY_ORG/*

# before_deploy:
#   - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
