sudo: required
services:
  - docker
env:
  matrix:
    - CHANNEL=stable LANGUAGE=python2 BASE=ubuntu16
    - CHANNEL=edge LANGUAGE=python2 BASE=ubuntu16
    - CHANNEL=stable LANGUAGE=python3 BASE=ubuntu16
    - CHANNEL=edge LANGUAGE=python3 BASE=ubuntu16
    - CHANNEL=stable LANGUAGE=python2 BASE=ubuntu17
    - CHANNEL=edge LANGUAGE=python2 BASE=ubuntu17
    - CHANNEL=stable LANGUAGE=python3 BASE=ubuntu17
    - CHANNEL=edge LANGUAGE=python3 BASE=ubuntu17
  global:
    - REGISTRY_ORG=sd2e
    - REGISTRY_USER=sd2etest
    # REGISTRY_PASS=...

script:
  - make base-build CHANNEL=$CHANNEL BASE=$BASE
  - make languages-build CHANNEL=$CHANNEL LANGUAGE=$LANGUAGE BASE=$BASE
  - make reactors-build CHANNEL=$CHANNEL LANGUAGE=$LANGUAGE

after_script:
  - docker images ${REGISTRY_ORG}/*

deploy:
  provider: script
  script: for IMG in `docker images ${REGISTRY_ORG}/* | awk '{ print $1":"$2 }'`; do docker push ${IMG}; done
  on:
    branch: master
