FROM alpine:3.6

ARG CHANNEL=stable
ARG BASE=alpine36
ARG LANGUAGE=python2

ARG AGAVEPY_BRANCH=develop
ARG PYTHON_PYTHON_PIP_VERSION=9.0.3

RUN apk add --update alpine-sdk musl python python-dev py-pip && \
    rm /var/cache/apk/*

RUN pip install --upgrade pip==${PYTHON_PYTHON_PIP_VERSION}

ADD requirements-${CHANNEL}.txt /requirements.txt
RUN pip install --upgrade --no-cache-dir --upgrade -r /requirements.txt
