FROM sd2e/base:ubuntu17
LABEL ORG=sd2e.org IMAGE=java8

ARG LANGUAGE=java8
ARG AGAVEPY_BRANCH=master

RUN sed -i -re 's/([a-z]{2}\.)?archive.ubuntu.com|security.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list

RUN apt-get -y update && \
    apt-get -y install build-essential \
    openjdk-8-jdk-headless \
    ant \
    gradle \
    maven \
    libssl-dev \
    libffi-dev  && \
    apt-get clean
