FROM sd2e/python2:miniconda

ARG LANGUAGE=python2-miniconda
ARG VERSION=0.5.5
ARG AGAVEPY_BRANCH=develop

# Discoverable version inside the container
RUN echo "TACC.cloud Apps\nType: ${LANGUAGE}\nVersion: ${VERSION}" > /etc/apps-VERSION
# Helpful env variable
ENV APPS_VERSION=${VERSION}
