name: Docker publish

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

  pull_request:
    # run tests only for pull requests to `master`
    branches:
      - master

  workflow_dispatch:

env:
  # Docker image
  # DOCKER_PASSWORD accessible via secrets
  DOCKER_USER: enho
  DOCKER_IMAGE: enho/reactors:python3

  # Tapis credentials for testing
  # TAPIS_PASSWORD accessible via secrets
  TAPIS_BASE_URL: https://api.sd2e.org/
  TAPIS_USERNAME: eho

jobs:

  test:
    name: Build Docker image and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install cookiecutter
      - name: Build image
        run: DOCKER_IMAGE=${DOCKER_IMAGE} make -B image
      - name: Run tests
        run: |
          echo "building DOCKER_IMAGE=${DOCKER_IMAGE}"
          docker run --rm -e TAPIS_BASE_URL=${TAPIS_BASE_URL} \
            -e TAPIS_USERNAME=${TAPIS_USERNAME} \
            -e TAPIS_PASSWORD=${{ secrets.TAPIS_PASSWORD }} \
            ${DOCKER_IMAGE}

  push:
    name: Push Docker image to Docker Hub
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          push: true
          username: $DOCKER_USER
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: $DOCKER_IMAGE