name: Docker publish

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

  pull_request:
    # run tests only for pull requests to `master`
    branches:
      - master

  workflow_dispatch:

env:
  DOCKER_ORG: enho
  DOCKER_REPO: reactors
  DOCKER_TAG: python3
  DOCKER_IMAGE: ${DOCKER_ORG}/${DOCKER_REPO}:${DOCKER_TAG}

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install cookiecutter
      - name: Run tests
        run: DOCKER_IMAGE=${DOCKER_IMAGE} make -B tests

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: DOCKER_IMAGE=${DOCKER_IMAGE} make image

      - name: Log into registry
        run: |
          GH_ACTOR=${{ github.actor }}
          echo GH_ACTOR=$GH_ACTOR
          # TODO: enter secrets
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u $GH_ACTOR --password-stdin

      - name: Push image
        run: |
          # IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          # IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          echo DOCKER_IMAGE=${DOCKER_IMAGE}
          docker push ${DOCKER_IMAGE}
