name: Docker publish

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

  pull_request:
    # run tests only for pull requests to `master`
    branches:
      - master

env:
  # Docker image
  # DOCKER_PASSWORD accessible via secrets
  DOCKER_USER: enho
  DOCKER_IMAGE: enho/reactors:python3

  # Tapis credentials for testing
  # TAPIS_PASSWORD accessible via secrets
  TAPIS_BASE_URL: https://api.sd2e.org/
  TAPIS_USER: eho
  TAPIS_CLIENT: _cli-sd2e-actions-docker-publish

jobs:

  build-test-push:
    name: Build, test, and push Docker image 
    runs-on: ubuntu-latest
    steps:
      
      # install dependencies
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install cookiecutter
        run: python -m pip install -q cookiecutter git+https://github.com/TACC-Cloud/tapis-cli
      - name: Get default actor context
        run: |
          python -m cookiecutter --no-input -fc main --directory sd2e_base \
            https://github.com/TACC-Cloud/cc-tapis-v2-actors.git \
            name=default_actor_context alias=default_actor_context
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # build
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          pull: true
          push: false
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}
          tags: ${{ env.DOCKER_IMAGE }}

      # test
      - name: Authenticate Tapis client
        run: |
          touch ~/.tapis_firstrun
          tapis auth init --no-git --no-registry \
            --client-name $TAPIS_CLIENT --api-server $TAPIS_BASE_URL \
            --username $TAPIS_USER --password ${{ secrets.TAPIS_PASSWORD }} 
      - name: Test image using default CMD
        run: |
          TAPIS_TOKEN="$(tapis auth show -f json | jq -rc .access_token)"
          [ -z $TAPIS_TOKEN ] && echo failed to generate Tapis access token && exit 1
          docker run --rm \
            -e _abaco_access_token=${TAPIS_TOKEN} \
            -e _abaco_api_server=${TAPIS_BASE_URL} \
            ${{ env.DOCKER_IMAGE }}
      
      # push
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}
