name: Docker publish

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
    paths-ignore:
      - '**.md'

  pull_request:
    # run tests only for pull requests to `master`
    branches:
      - master
    paths-ignore:
      - '**.md'

env:
  # Docker image
  # DOCKER_PASSWORD accessible via secrets
  DOCKER_USER: enho
  DOCKER_ORG: enho
  DOCKER_REPO: reactors
  DOCKER_TAG: python3

jobs:

  build-test-push:
    name: Build, test, and push Docker image 
    runs-on: ubuntu-latest
    steps:
      
      # install dependencies
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # build & test
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          pull: true
          load: true
          push: false
          tags: ${{ env.DOCKER_ORG }}/${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }}
      - name: Test image using default CMD
        run: docker run --rm ${{ env.DOCKER_ORG }}/${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }}
      
      # push
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_ORG }}/${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }}
            ${{ env.DOCKER_ORG }}/${{ env.DOCKER_REPO }}:latest
