name: Docker publish

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

  pull_request:
    # run tests only for pull requests to `master`
    branches:
      - master

env:
  # TODO
  IMAGE_NAME: reactors
  IMAGE_TAG: python3

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: make -B tests

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: make image

      - name: Log into registry
        run: |
          GH_ACTOR=${{ github.actor }}
          echo GH_ACTOR=$GH_ACTOR
          # TODO: enter secrets
          # TODO: config Docker org
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u $GH_ACTOR --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          echo IMAGE_ID=$IMAGE_ID
          echo IMAGE_TAG=$IMAGE_TAG

          # TODO: consider using make
          docker tag $IMAGE_NAME $IMAGE_ID:$IMAGE_TAG
          docker push $IMAGE_ID:$IMAGE_TAG
